name: real-estate-scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '00 05 * * *'

jobs:
  real-estate-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install lxml matplotlib pandas requests
    - name: Run scraper
      env:
        REDFIN_URL: ${{ secrets.REDFIN_URL }}
        ZILLOW_URL: ${{ secrets.ZILLOW_URL }}
        SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
      run: python scrape_with_premium.py
    - name: Commit and push if it changed
      run: |-
        git config --global user.name "scraper-bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Scraped at ${timestamp}" || exit 0
        git push
    - name: Set workflow status
      # Fail with clear error if NaN is present in last line of data.csv
      run: |
        if tail -1 data.csv | grep -q NaN; then
          echo "ERROR: NaN detected in last line of data.csv. Scraper may have failed or returned incomplete data."
          exit 1
        else
          echo "Scrape successful: No NaN detected in last line of data.csv."
        fi
